# Workflow for building and deploying a Nuxt site to GitHub Pages using pnpm
name: Deploy Nuxt site to Pages

on:
  # Trigger workflow on push to master branch
  push:
    branches: ["master"]
  # Manual trigger via the Actions tab
  workflow_dispatch:

# Set permissions for deploying to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one concurrent deployment of this workflow
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Setup pnpm
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      # Step 3: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      # Step 4: Nuxt configuration for GitHub Pages
      - name: Configure Nuxt for static export
        uses: actions/configure-pages@v5
        with:
          static_site_generator: nuxt

      # Step 5: Restore cache for dependencies and build output
      - name: Restore dependencies and build cache
        uses: actions/cache@v4
        with:
          path: |
            dist
            .nuxt
            node_modules
          key: ${{ runner.os }}-pnpm-nuxt-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-nuxt-

      # Step 6: Install dependencies using pnpm
      - name: Install project dependencies
        run: pnpm install

      # Step 7: Build the static site with Nuxt
      - name: Generate static site with Nuxt
        run: pnpm generate

      # Step 8: Upload build to GitHub Pages artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  # Deployment job
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4